export const API_BASE_URL = "https://api.freeapi.app/";

export const STORAGE_KEYS = {
  USER_DATA: "USER_DATA",
  BOOKMARKS: "BOOKMARKS",
  ENROLLED_COURSES: "ENROLLED_COURSES",
  COURSE_PROGRESS: "COURSE_PROGRESS",
  STREAK_DATA: "streak_data",
  ACTIVITY_LOG: "activity_log",
  BADGES_EARNED: "badges_earned",
  LAST_OPEN_TIMESTAMP: "LAST_OPEN_TIMESTAMP",
  BOOKMARK_MILESTONE_NOTIFIED: "BOOKMARK_MILESTONE_NOTIFIED",
  PROFILE_IMAGE: "PROFILE_IMAGE",
  THEME_MODE: "theme_mode",
  BIOMETRIC_ENABLED: "biometric_enabled",
  BIOMETRIC_PROMPT_SHOWN: "biometric_prompt_shown",
};

export const SECURE_KEYS = {
  AUTH_TOKEN: "AUTH_TOKEN",
  REFRESH_TOKEN: "refresh_token",
};
